service: utd-grades

custom:
  serverless-offline:
    httpPort: 4000
  envVars: ${file(env.json)}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'development'}
  stackTags:
    environment: ${self:provider.stage}
    project: utd-grades
  environment:
    DB_NAME: ${env:DB_NAME, self:custom.envVars.DB_NAME}
    DB_USER: ${env:DB_USER, self:custom.envVars.DB_USER}
    DB_PASS: ${env:DB_PASS, self:custom.envVars.DB_PASS}
    DB_HOST: ${env:DB_HOST, self:custom.envVars.DB_HOST}

package:
  exclude:
    - '**/__tests__/**'

functions:
  getSection:
    handler: services/section/get/handler.handler
    events:
      - http:
          path: section/{id}
          method: get 
          request: 
            parameters: 
              paths: 
                id: true
          cors: true
  
  findSection:
    handler: services/section/find/handler.handler
    events:
      - http:
          path: section
          method: get
          cors: true

plugins:
  - serverless-offline
